services:
  backend:
    build:
      context: ./backend
    container_name: dataset-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: dataset-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
